services:
    _defaults:
        autowire: true
        autoconfigure: true

    AppBundle\UseCase\RegisterUser: ~
    AppBundle\UseCase\GetUserProfileUseCase: ~
    AppBundle\UseCase\FollowUser: ~
    AppBundle\UseCase\UnfollowUser: ~

    Core\Repository\UserRepositoryInterface:
      class: AppBundle\Repository\DoctrineUserRepository
      factory: ['@doctrine.orm.entity_manager', getRepository]
      arguments:
          - AppBundle\Entity\User

    encoder.password:
        class: Symfony\Component\Security\Core\Encoder\BCryptPasswordEncoder
        arguments:
            - 12

    provider.user_token_view:
        class: AppBundle\Provider\UserTokenViewProvider
        arguments:
            - '@lexik_jwt_authentication.encoder'
